- Name: 10 random numbers
  Binding: runif(10, 0, 10)
- Name: Say Something Nice
  id: 97
  Description: A demo of cool things
  Binding: praise::praise
  Interactive: true
- Name: Remind me where I am
  Binding: |
    current_dir = getwd()
    message("Working directory: ", current_dir)
  Interactive: false
- Name: A Random Number Between 0 and 1
  Description: Another demo
  Binding: runif(1, 0, 1)
  Interactive: true
